development:
  es:
    host: localhost:9200
  port: 5000
  redis:
    host: localhost
    port: 6379
  mongo:
    host: localhost
  amqp: amqp://guest:guest@127.0.0.1
  orient:
    host: 104.236.193.239
    port: 2424
    username: root
    password: password
production:
  es:
    host: 127.0.0.1
  port: 8081
  redis:
    host: 127.0.0.1
    port: 6379
  mongo:
    host: 127.0.0.1
    user: hi
    pwd: password
  cookie_secret: 14CD746D-B1B8-4B9C-8A33-A8447735BF3C
  amqp: amqp://guest:guest@127.0.0.1
default:
  cookie_secret: 14CD746D-B1B8-4B9C-8A33-A8447735BF3C
  auth:
    fb:
        app_id: 111111
        secret: secret
    vk:
        app_id: 111111
        secret: khrTr5HtqRy9nUbPLcVg
