source 'https://rubygems.org'

gem 'asset_sync'
gem 'bcrypt', '~> 3.1.7'
gem 'coffee-rails', '~> 4.1.0'
gem 'devise'
gem 'devise-i18n'
gem 'fog-aws'
gem 'haml'
gem 'feedjira'
gem 'nokogiri'
gem 'inherited_resources'
gem 'faraday'
gem 'connection_pool'
gem 'normalize_url'
gem 'kgio'
gem 'open_uri_redirections'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'momentjs-rails'
gem 'pg'
gem 'rails', '~> 4.2'
gem 'rails-i18n'
gem 'russian'
gem 'sass-rails', '~> 5.0'
gem 'session_injector', :github => 'pvf/session-injector'
gem 'sqlite3'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'redis-session-store'
gem 'slim'
gem 'stylus'
gem 'addressable'
gem 'angular_rails_csrf'
gem 'crono'
gem 'puma'
gem 'yajl-ruby', require: 'yajl'
gem 'vk-ruby', :github => 'zinenko/vk-ruby'

group :development, :test do
  gem 'annotate', :github => 'ctran/annotate_models'
  gem 'byebug'
  gem 'railroady'
  gem 'spring'
  gem 'unicorn'
  gem 'web-console', '~> 2.0'
end

if `whoami`.strip != 'ec2-user'
  gem 'v-shared', '~>0.1', :path => '..', :branch => :master, :ref => :HEAD
else
  gem 'v-shared', '~>0.1', :git => 'git@bitbucket.org:N-1/v-shared.git', :branch => :master
end

group :development do
  gem 'erb2haml'
end

group :doc do
  gem 'sdoc', '~> 0.4.0'
end
