development:
  pg:
    host     : localhost
    user     : spynotify
    password : spynotify
    database : spynotify
    charset  : 'utf8'
  redis:
    host     : localhost
    port     : 6379
production:
  pg:
    host     : spynotify.cxyt3hsiggxl.eu-central-1.rds.amazonaws.com
    user     : spynotify
    password : spynotify
    database : spynotify
    charset  : utf8
  redis:
    host     : runexto.frxufj.0001.euc1.cache.amazonaws.com
    port     : 6379
default:
